import anygrad

print("-"*10, " Float32 ", "-"*10)
print("-"*5, " Add ", "-"*5)
a = anygrad.Tensor([1,2,3], requires_grad=True)
b = anygrad.Tensor([1,2,3], requires_grad=True)
c = a + b
c.sum().backward()
print("a + b = ", c)
print("a.grad", a.grad)
print("b.grad", b.grad)
print()
print("-"*5, " Sub ", "-"*5)
a = anygrad.Tensor([1,2,3], requires_grad=True)
b = anygrad.Tensor([1,2,3], requires_grad=True)
c = a - b
c.sum().backward()
print("a - b = ", c)
print("a.grad", a.grad)
print("b.grad", b.grad)
print()
print("-"*5, " Mul ", "-"*5)
a = anygrad.Tensor([1,2,3], requires_grad=True)
b = anygrad.Tensor([1,2,3], requires_grad=True)
c = a * b
c.sum().backward()
print("a * b = ", c)
print("a.grad", a.grad)
print("b.grad", b.grad)
print()
print("-"*5, " Div ", "-"*5)
a = anygrad.Tensor([1,2,3], requires_grad=True)
b = anygrad.Tensor([1,2,3], requires_grad=True)
c = a / b
c.sum().backward()
print("a / b = ", c)
print("a.grad", a.grad)
print("b.grad", b.grad)
print()
print("-"*5, " Pow ", "-"*5)
a = anygrad.Tensor([1,2,3], requires_grad=True)
b = anygrad.Tensor([1,2,3], requires_grad=True)
c = a ** b
c.sum().backward()
print("a ** b = ", c)
print("a.grad", a.grad)
print("b.grad", b.grad)

print("-"*20)

print("-"*10, " Float64 ", "-"*10)
print("-"*5, " Add ", "-"*5)
a = anygrad.Tensor([1,2,3], dtype=anygrad.float64, requires_grad=True)
b = anygrad.Tensor([1,2,3], dtype=anygrad.float64, requires_grad=True)
c = a + b
c.sum().backward()
print("a + b = ", c)
print("a.grad", a.grad)
print("b.grad", b.grad)
print()
print("-"*5, " Sub ", "-"*5)
a = anygrad.Tensor([1,2,3], dtype=anygrad.float64, requires_grad=True)
b = anygrad.Tensor([1,2,3], dtype=anygrad.float64, requires_grad=True)
c = a - b
c.sum().backward()
print("a - b = ", c)
print("a.grad", a.grad)
print("b.grad", b.grad)
print()
print("-"*5, " Mul ", "-"*5)
a = anygrad.Tensor([1,2,3], dtype=anygrad.float64, requires_grad=True)
b = anygrad.Tensor([1,2,3], dtype=anygrad.float64, requires_grad=True)
c = a * b
c.sum().backward()
print("a * b = ", c)
print("a.grad", a.grad)
print("b.grad", b.grad)
print()
print("-"*5, " Div ", "-"*5)
a = anygrad.Tensor([1,2,3], dtype=anygrad.float64, requires_grad=True)
b = anygrad.Tensor([1,2,3], dtype=anygrad.float64, requires_grad=True)
c = a / b
c.sum().backward()
print("a / b = ", c)
print("a.grad", a.grad)
print("b.grad", b.grad)
print()
print("-"*5, " Pow ", "-"*5)
a = anygrad.Tensor([1,2,3], dtype=anygrad.float64, requires_grad=True)
b = anygrad.Tensor([1,2,3], dtype=anygrad.float64, requires_grad=True)
c = a ** b
c.sum().backward()
print("a ** b = ", c)
print("a.grad", a.grad)
print("b.grad", b.grad)
