name: Build & Publish anygrad to PyPI
on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Upgrade pip, setuptools, wheel, and install build
        run: |
          python -m pip install --upgrade pip setuptools wheel build
      - name: Build distributions (wheel and sdist) on Windows
        run: python -m build
      - name: List generated files on Windows
        run: dir dist
      - name: Upload Windows Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-dist
          path: dist/*

  build-macos:
    name: Build on macOS
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Upgrade pip, setuptools, wheel, and install build
        run: |
          python -m pip install --upgrade pip setuptools wheel build
      - name: Build distributions (wheel and sdist) on macOS
        run: python -m build
      - name: List generated files on macOS
        run: ls -lh dist/
      - name: Upload macOS Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-dist
          path: dist/*

  publish:
    name: Combine and Publish Distributions to PyPI
    runs-on: macos-latest
    needs: [build-windows, build-macos]
    steps:
      - name: Download Windows Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-dist
          path: dist/
      - name: Download macOS Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: macos-dist
          path: dist/
      - name: List combined distribution files
        run: ls -lh dist/
      - name: Upgrade pip, setuptools, wheel and install twine
        run: python -m pip install --upgrade pip setuptools wheel twine
      - name: Check distributions before upload
        run: python -m twine check dist/*
      - name: Publish to PyPI
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload dist/* --username __token__ --password "$PYPI_API_TOKEN"
