name: Build & Publish anygrad to PyPI

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-windows:
    name: Build & Publish on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine

      - name: Build distributions (sdist & wheel)
        run: python -m build --sdist --wheel

      - name: Verify generated distributions
        run: dir dist

      - name: Publish to PyPI from Windows
        shell: bash
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload dist/* -u __token__ -p "$PYPI_API_TOKEN"

  build-macos:
    name: Build & Publish on macOS
    runs-on: macos-latest
    needs: build-windows

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine

      - name: Build distributions (sdist & wheel)
        run: python -m build --sdist --wheel

      - name: Verify generated distributions
        run: ls -lh dist/

      - name: Publish to PyPI from macOS
        shell: bash
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload dist/* -u __token__ -p "$PYPI_API_TOKEN"
