name: Publish anygrad to PyPI

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-and-publish:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine pybind11

      - name: Verify pybind11 installation
        run: python -m pip show pybind11

      - name: Build anygrad package
        run: python -m build

      - name: Publish anygrad to PyPI via Twine
        if: github.event_name == 'release'
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload dist/* -u __token__ -p $PYPI_API_TOKEN
