name: Publish anygrad to PyPI

on:
  release:
    types: [created]  
  workflow_dispatch:  

jobs:
  build-and-publish:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write  
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x" 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pybind11
          python -m pip install build twine

      - name: Verify pybind11 installation
        run: |
          python -m pip show pybind11

      - name: Build anygrad package
        run: |
          python -m build

      - name: Publish anygrad to PyPI
        if: github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
