name: Build & Publish anygrad to PyPI

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-and-publish:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine

      - name: Build source distribution (.tar.gz)
        run: python -m build --sdist

      - name: Build wheel (.whl)
        run: python -m build --wheel

      - name: Verify generated distributions
        run: ls -lh dist/

      - name: Publish to PyPI
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload dist/* -u __token__ -p $PYPI_API_TOKEN
