name: Run Test Workflow

on:
  push:
  pull_request:

jobs:
  run-scripts-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install numpy
          python -m pip install --upgrade pip setuptools wheel

      - name: Set execution permission for scripts
        run: chmod +x setup.sh /test/run/tensor_test.sh

      - name: Run setup.sh
        run: ./setup.sh

      - name: Run test files
        run: |
          ./test/run/tensor_test.sh

  run-scripts-windows:
      runs-on: windows-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
    
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.10"
    
        - name: Set UTF-8 encoding
          run: chcp 65001
    
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install numpy
            python -m pip install --upgrade setuptools wheel
    
        - name: Run setup.sh
          shell: bash
          run: bash setup.sh
    
        - name: Run test files
          shell: bash
          run: |
            bash test/run/tensor_test.sh
